[project]
name = "mcp-log-query"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.13.1",
    "mcp>=1.22.0",
    "openai>=2.8.1",
    "requests>=2.31.0",
]
